FROM docker.elastic.co/beats/filebeat:6.2.4
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN mkdir /usr/share/filebeat/dockerlogs \
    && chown -R root /usr/share/filebeat/ \
    && chmod -R go-w /usr/share/filebeat/
