FROM docker.elastic.co/kibana/kibana:6.2.4
RUN git clone https://github.com/lmangani/timelion-prometheus && cd timelion-prometheus \
    && VERSION="6.2.4" ./release.sh \
    && kibana-plugin install ./timelion-prometheus-1.0.0.zip \
    && cd - && rm -rf timelion-prometheus
